### ISSUE TITLE
Unable to launch or generate .sln file in 4.23

### ISSUE THREAD

**Issue by KewTeacher** [tranek/GASDocumentation#18]
HI, I'm having trouble getting this working in 4.23. When I try to create an .sln 4.23 I get this message 

> Running C:/Program Files/Epic Games/UE_4.23/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="D:/Git Hub/GASDocumentation/GASDocumentation.uproject" -game -rocket -progress -log="D:\Git Hub\GASDocumentation/Saved/Logs/UnrealVersionSelector-2020.02.25-12.18.01.log"
Discovering modules, targets and source code for project...
While compiling D:\Git Hub\GASDocumentation\Intermediate\Build\BuildRules\GASDocumentationModuleRules.dll:
d:\Git Hub\GASDocumentation\Source\GASDocumentationEditor.Target.cs(11,3) : error CS0103: The name 'DefaultBuildSettings' does not exist in the current context
d:\Git Hub\GASDocumentation\Source\GASDocumentationEditor.Target.cs(11,26) : error CS0103: The name 'BuildSettingsVersion' does not exist in the current context
ERROR: Unable to compile source files.

**Comment by KewTeacher** [comment]
thanks, I just installed 4.24 and it's working fine. thanks so much for this example, I'm teaching high schoolers game dev and have been struggling with the ARPG epic example.

**Comment by tranek** [comment]
You're welcome! We have a healthy little community around GAS in its own text channel on the Unreal Slackers Discord server. It's a good place to go if you have questions.

https://unrealslackers.org/

Also check out my latest FPS/TPS sample project, GASShooter, which shows advanced GAS techniques related to using guns.

https://github.com/tranek/GASShooter
